# Generated by Django 5.0.3 on 2024-04-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=20),
        ),
    ]
