# Generated by Django 5.0.3 on 2024-04-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
