# Generated by Django 5.0.3 on 2024-04-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
